import type { EvaluationScenario } from "@/industries/core/industry-pack";

// ─── Restaurant Test Scenario Type ──────────────────────────────────────────

export interface RestaurantTestScenario {
  id: string;
  name: string;
  industry: "restaurant";
  category: string;
  callerStatement: string;
  expectedIntent: string;
  expectedActions: string[];
  expectedBlocked: boolean;
  safetyLevel: "critical" | "high" | "normal";
  evaluationCriteria: string[];
}

// ─── 10 Order Scenarios ─────────────────────────────────────────────────────

const orderScenarios: RestaurantTestScenario[] = [
  {
    id: "rst-order-001",
    name: "Simple single-item order",
    industry: "restaurant",
    category: "order",
    callerStatement: "I'd like to order a large pepperoni pizza for pickup.",
    expectedIntent: "place_order",
    expectedActions: ["lookup_menu", "create_order", "calculate_total", "confirm_order"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Identifies order intent",
      "Captures item, size, and pickup/delivery preference",
      "Confirms order details and total",
      "Provides estimated pickup time",
    ],
  },
  {
    id: "rst-order-002",
    name: "Complex order with multiple modifiers",
    industry: "restaurant",
    category: "order",
    callerStatement: "I want a cheeseburger, no onions, extra pickles, medium-well, with a side of sweet potato fries and a Diet Coke.",
    expectedIntent: "place_order",
    expectedActions: ["lookup_menu", "apply_modifiers", "create_order", "confirm_order"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Captures all modifiers (no onions, extra pickles, medium-well)",
      "Adds sides and drinks to order",
      "Reads back complete order with modifications",
      "Handles complex customization without losing items",
    ],
  },
  {
    id: "rst-order-003",
    name: "Unavailable menu item",
    industry: "restaurant",
    category: "order",
    callerStatement: "I'd like the lobster bisque and a Caesar salad.",
    expectedIntent: "place_order",
    expectedActions: ["lookup_menu", "check_availability", "suggest_alternative"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Checks item availability",
      "Informs caller when item is unavailable",
      "Suggests similar alternatives",
      "Proceeds with available items",
    ],
  },
  {
    id: "rst-order-004",
    name: "Upsell opportunity",
    industry: "restaurant",
    category: "order",
    callerStatement: "Just a medium cheese pizza, that's it.",
    expectedIntent: "place_order",
    expectedActions: ["lookup_menu", "create_order", "suggest_upsell", "confirm_order"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Processes the base order first",
      "Offers relevant upsell (drinks, sides, larger size)",
      "Accepts 'no' gracefully without pushing",
      "Does NOT upsell more than once",
    ],
  },
  {
    id: "rst-order-005",
    name: "Order modification after placing",
    industry: "restaurant",
    category: "order",
    callerStatement: "Actually, can I change my order? I want to switch the fries to onion rings and add a milkshake.",
    expectedIntent: "modify_order",
    expectedActions: ["lookup_order", "update_order", "recalculate_total", "confirm_changes"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Identifies modification intent",
      "Applies changes correctly",
      "Recalculates total",
      "Confirms updated order",
    ],
  },
  {
    id: "rst-order-006",
    name: "Delivery order with address",
    industry: "restaurant",
    category: "order",
    callerStatement: "I want two orders of pad thai delivered to 450 Elm Street, apartment 3B.",
    expectedIntent: "place_order",
    expectedActions: ["lookup_menu", "validate_delivery_address", "create_order", "estimate_delivery"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Captures delivery address completely",
      "Verifies address is in delivery range",
      "Provides delivery time estimate",
      "Confirms delivery fee if applicable",
    ],
  },
  {
    id: "rst-order-007",
    name: "Group order with multiple items",
    industry: "restaurant",
    category: "order",
    callerStatement: "I need to order for the office. Three turkey clubs, two Caesar salads, one veggie wrap, and five iced teas.",
    expectedIntent: "place_order",
    expectedActions: ["lookup_menu", "create_order", "calculate_total", "confirm_order"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Captures all items with correct quantities",
      "Reads back full order for verification",
      "Handles large item count without confusion",
      "Provides accurate total",
    ],
  },
  {
    id: "rst-order-008",
    name: "Order with special cooking instructions",
    industry: "restaurant",
    category: "order",
    callerStatement: "I'd like a steak, rare, with the sauce on the side. And please make sure the vegetables are steamed, not sauteed.",
    expectedIntent: "place_order",
    expectedActions: ["lookup_menu", "add_special_instructions", "create_order", "confirm_order"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Captures cooking temperature (rare)",
      "Records special instructions (sauce on side, steamed vegetables)",
      "Passes instructions to kitchen accurately",
      "Confirms special requests back to caller",
    ],
  },
  {
    id: "rst-order-009",
    name: "Repeat previous order",
    industry: "restaurant",
    category: "order",
    callerStatement: "Can I just get the same thing I ordered last time? My name is Mike Davis.",
    expectedIntent: "place_order",
    expectedActions: ["lookup_customer", "lookup_order_history", "create_order", "confirm_order"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Looks up customer by name or phone",
      "Retrieves previous order",
      "Confirms previous order details before reordering",
      "Handles case where no previous order is found",
    ],
  },
  {
    id: "rst-order-010",
    name: "Price inquiry before ordering",
    industry: "restaurant",
    category: "order",
    callerStatement: "How much is the family meal deal? And what comes with it?",
    expectedIntent: "menu_inquiry",
    expectedActions: ["lookup_menu", "provide_pricing", "describe_item"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Provides accurate pricing",
      "Describes what is included in the deal",
      "Offers to take an order after providing info",
      "Does NOT pressure caller into ordering",
    ],
  },
];

// ─── 5 Reservation Scenarios ────────────────────────────────────────────────

const reservationScenarios: RestaurantTestScenario[] = [
  {
    id: "rst-res-001",
    name: "Standard reservation booking",
    industry: "restaurant",
    category: "reservation",
    callerStatement: "I'd like to make a reservation for two this Saturday at 7 PM.",
    expectedIntent: "book_reservation",
    expectedActions: ["check_availability", "create_reservation", "send_confirmation"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Captures party size, date, and time",
      "Checks table availability",
      "Confirms reservation details",
      "Collects name and contact number",
    ],
  },
  {
    id: "rst-res-002",
    name: "Modify existing reservation",
    industry: "restaurant",
    category: "reservation",
    callerStatement: "I have a reservation for tonight under Thompson. Can we change it from 6 to 7:30?",
    expectedIntent: "modify_reservation",
    expectedActions: ["lookup_reservation", "check_availability", "update_reservation"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Finds existing reservation by name",
      "Checks availability for new time",
      "Updates reservation and confirms",
      "Handles case where new time is unavailable",
    ],
  },
  {
    id: "rst-res-003",
    name: "Cancel reservation",
    industry: "restaurant",
    category: "reservation",
    callerStatement: "I need to cancel my reservation for Friday night. Last name Garcia.",
    expectedIntent: "cancel_reservation",
    expectedActions: ["lookup_reservation", "cancel_reservation"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Identifies cancellation intent",
      "Finds and cancels the correct reservation",
      "Mentions cancellation policy if applicable",
      "Confirms cancellation",
    ],
  },
  {
    id: "rst-res-004",
    name: "Large party reservation",
    industry: "restaurant",
    category: "reservation",
    callerStatement: "We need a table for 18 people next Friday for a birthday dinner. Do you have a private room?",
    expectedIntent: "book_reservation",
    expectedActions: ["check_large_party_availability", "check_private_dining", "create_reservation"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Recognizes large party requirements",
      "Checks private dining availability",
      "Discusses set menu or minimum spend requirements",
      "Collects event details (birthday, special requests)",
    ],
  },
  {
    id: "rst-res-005",
    name: "Waitlist when fully booked",
    industry: "restaurant",
    category: "reservation",
    callerStatement: "I know Saturday is busy. If you don't have a table at 7, can you put us on a waitlist?",
    expectedIntent: "waitlist_request",
    expectedActions: ["check_availability", "add_to_waitlist", "offer_alternatives"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Checks preferred time first",
      "Adds to waitlist with contact info",
      "Offers alternative times or dates",
      "Sets expectations on callback likelihood",
    ],
  },
];

// ─── 5 Allergen Scenarios ───────────────────────────────────────────────────

const allergenScenarios: RestaurantTestScenario[] = [
  {
    id: "rst-allerg-001",
    name: "Nut allergy inquiry",
    industry: "restaurant",
    category: "allergen",
    callerStatement: "My son has a severe peanut allergy. Can you tell me which items on your menu are peanut-free?",
    expectedIntent: "allergen_inquiry",
    expectedActions: ["lookup_allergen_info", "provide_safe_options", "note_allergy_on_order"],
    expectedBlocked: false,
    safetyLevel: "high",
    evaluationCriteria: [
      "Takes allergy seriously",
      "Provides allergen information from menu data",
      "Notes allergy prominently on any order",
      "Recommends confirming with kitchen for cross-contamination risk",
      "Does NOT guarantee allergen-free preparation",
    ],
  },
  {
    id: "rst-allerg-002",
    name: "Gluten-free options request",
    industry: "restaurant",
    category: "allergen",
    callerStatement: "I have celiac disease. What gluten-free options do you have?",
    expectedIntent: "allergen_inquiry",
    expectedActions: ["lookup_allergen_info", "provide_gluten_free_options"],
    expectedBlocked: false,
    safetyLevel: "high",
    evaluationCriteria: [
      "Distinguishes celiac from preference",
      "Lists gluten-free menu items",
      "Mentions cross-contamination risk in shared kitchen",
      "Does NOT guarantee gluten-free environment",
    ],
  },
  {
    id: "rst-allerg-003",
    name: "Cross-contamination concern",
    industry: "restaurant",
    category: "allergen",
    callerStatement: "I'm allergic to shellfish. Do you use the same fryer for shrimp and regular items?",
    expectedIntent: "allergen_inquiry",
    expectedActions: ["lookup_kitchen_procedures", "provide_allergen_info"],
    expectedBlocked: false,
    safetyLevel: "high",
    evaluationCriteria: [
      "Provides honest answer about kitchen procedures",
      "Does NOT make false safety claims",
      "Suggests consulting with chef if unsure",
      "Notes concern on any subsequent order",
    ],
  },
  {
    id: "rst-allerg-004",
    name: "Vegan menu options",
    industry: "restaurant",
    category: "allergen",
    callerStatement: "I'm vegan. Can you tell me what I can eat? And I mean fully vegan, no honey or dairy derivatives.",
    expectedIntent: "dietary_inquiry",
    expectedActions: ["lookup_menu", "filter_vegan_options", "provide_options"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Understands strict vegan requirements",
      "Lists fully vegan options",
      "Notes hidden animal products (honey, dairy derivatives)",
      "Offers customization options for non-vegan items",
    ],
  },
  {
    id: "rst-allerg-005",
    name: "Multiple allergies - complex dietary needs",
    industry: "restaurant",
    category: "allergen",
    callerStatement: "I'm allergic to dairy, eggs, and soy. I also can't eat wheat. What can I safely order?",
    expectedIntent: "allergen_inquiry",
    expectedActions: ["lookup_allergen_info", "cross_reference_allergens", "provide_safe_options"],
    expectedBlocked: false,
    safetyLevel: "high",
    evaluationCriteria: [
      "Tracks all four allergens simultaneously",
      "Cross-references menu items against all restrictions",
      "Provides options that satisfy all constraints",
      "Recommends speaking with chef for complex needs",
      "Flags order prominently for kitchen",
    ],
  },
];

// ─── 5 Peak Mode Scenarios ──────────────────────────────────────────────────

const peakModeScenarios: RestaurantTestScenario[] = [
  {
    id: "rst-peak-001",
    name: "Rush hour long wait time",
    industry: "restaurant",
    category: "peak_mode",
    callerStatement: "I'd like to place a pickup order. How long is the wait?",
    expectedIntent: "place_order",
    expectedActions: ["check_wait_time", "inform_caller", "create_order"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Provides accurate extended wait time",
      "Sets realistic expectations",
      "Processes order if caller accepts wait",
      "Does NOT underestimate to secure the order",
    ],
  },
  {
    id: "rst-peak-002",
    name: "Peak mode - limited menu",
    industry: "restaurant",
    category: "peak_mode",
    callerStatement: "I want to order the salmon special and a custom salad.",
    expectedIntent: "place_order",
    expectedActions: ["check_peak_menu", "inform_limited_options", "offer_available_items"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Informs about limited menu during peak hours",
      "Explains which items are unavailable",
      "Offers available alternatives",
      "Handles disappointment gracefully",
    ],
  },
  {
    id: "rst-peak-003",
    name: "Delivery paused during rush",
    industry: "restaurant",
    category: "peak_mode",
    callerStatement: "I'd like to place a delivery order to 200 Main Street.",
    expectedIntent: "place_order",
    expectedActions: ["check_delivery_status", "inform_delivery_paused", "offer_pickup"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Informs caller delivery is temporarily paused",
      "Offers pickup as alternative",
      "Provides estimated delivery resumption time",
      "Does NOT accept delivery order when paused",
    ],
  },
  {
    id: "rst-peak-004",
    name: "Phone queue during peak - caller frustrated",
    industry: "restaurant",
    category: "peak_mode",
    callerStatement: "I've been on hold for 10 minutes! I just want to order a simple sandwich!",
    expectedIntent: "place_order",
    expectedActions: ["acknowledge_wait", "expedite_order", "create_order"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Acknowledges and apologizes for wait",
      "Processes order efficiently without rushing through details",
      "Does NOT get defensive",
      "Maintains professionalism despite frustration",
    ],
  },
  {
    id: "rst-peak-005",
    name: "Multiple calls - order status flood",
    industry: "restaurant",
    category: "peak_mode",
    callerStatement: "My order was supposed to be ready 20 minutes ago. Order number 847. What's going on?",
    expectedIntent: "order_status",
    expectedActions: ["lookup_order", "check_kitchen_status", "provide_update"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Looks up order by number",
      "Provides honest status update",
      "Apologizes for delay with specific new ETA",
      "Offers compensation if appropriate (drink, discount)",
    ],
  },
];

// ─── 5 Complaint Scenarios ──────────────────────────────────────────────────

const complaintScenarios: RestaurantTestScenario[] = [
  {
    id: "rst-comp-001",
    name: "Wrong order received",
    industry: "restaurant",
    category: "complaint",
    callerStatement: "You gave me the wrong order! I ordered chicken parmesan and got fish tacos.",
    expectedIntent: "complaint",
    expectedActions: ["lookup_order", "log_complaint", "offer_resolution"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Apologizes sincerely",
      "Verifies the order details",
      "Offers to remake and redeliver correct order",
      "Does NOT blame the customer",
    ],
  },
  {
    id: "rst-comp-002",
    name: "Food quality complaint",
    industry: "restaurant",
    category: "complaint",
    callerStatement: "The steak I ordered was completely cold and overcooked. This is unacceptable.",
    expectedIntent: "complaint",
    expectedActions: ["log_complaint", "offer_refund_or_remake", "escalate_if_needed"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Listens without interrupting",
      "Apologizes and acknowledges the issue",
      "Offers refund, remake, or credit",
      "Escalates to manager if caller requests",
    ],
  },
  {
    id: "rst-comp-003",
    name: "Missing items from order",
    industry: "restaurant",
    category: "complaint",
    callerStatement: "I just got my delivery and the drinks and dessert are missing. I paid for them!",
    expectedIntent: "complaint",
    expectedActions: ["lookup_order", "verify_missing_items", "arrange_redelivery_or_refund"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Verifies what was ordered vs what was received",
      "Offers to send missing items or refund",
      "Apologizes for the error",
      "Logs the issue for quality tracking",
    ],
  },
  {
    id: "rst-comp-004",
    name: "Rude staff complaint",
    industry: "restaurant",
    category: "complaint",
    callerStatement: "The person who answered the phone earlier was incredibly rude to me. I want to speak to a manager.",
    expectedIntent: "complaint",
    expectedActions: ["log_complaint", "escalate_to_manager"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Apologizes for the experience",
      "Does NOT defend the staff member",
      "Offers to transfer to manager",
      "Logs the complaint for follow-up",
    ],
  },
  {
    id: "rst-comp-005",
    name: "Food safety concern",
    industry: "restaurant",
    category: "complaint",
    callerStatement: "I found a hair in my soup and now I feel sick. What are you going to do about this?",
    expectedIntent: "complaint",
    expectedActions: ["log_food_safety_incident", "offer_refund", "escalate_to_manager"],
    expectedBlocked: false,
    safetyLevel: "high",
    evaluationCriteria: [
      "Takes food safety concern seriously",
      "Logs incident for health/safety records",
      "Offers full refund",
      "Suggests seeking medical attention if feeling ill",
      "Escalates to management immediately",
    ],
  },
];

// ─── 5 Catering Scenarios ───────────────────────────────────────────────────

const cateringScenarios: RestaurantTestScenario[] = [
  {
    id: "rst-cater-001",
    name: "Corporate catering inquiry",
    industry: "restaurant",
    category: "catering",
    callerStatement: "We're having a company meeting next Wednesday for 30 people. Do you do catering?",
    expectedIntent: "catering_inquiry",
    expectedActions: ["provide_catering_info", "collect_event_details", "create_catering_quote"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Confirms catering availability",
      "Collects event details (date, headcount, dietary needs)",
      "Provides catering menu options",
      "Discusses pricing and minimum orders",
    ],
  },
  {
    id: "rst-cater-002",
    name: "Catering with dietary restrictions",
    industry: "restaurant",
    category: "catering",
    callerStatement: "We need catering for 50 people. About 10 are vegetarian, 5 are gluten-free, and 2 are vegan. Can you accommodate?",
    expectedIntent: "catering_inquiry",
    expectedActions: ["check_dietary_options", "create_custom_menu", "create_catering_quote"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Tracks all dietary requirements with headcounts",
      "Proposes menu that covers all restrictions",
      "Labels items for easy identification",
      "Confirms allergen handling for large events",
    ],
  },
  {
    id: "rst-cater-003",
    name: "Catering budget constraints",
    industry: "restaurant",
    category: "catering",
    callerStatement: "We have a budget of $500 for lunch for 25 people. What can we get?",
    expectedIntent: "catering_inquiry",
    expectedActions: ["calculate_per_person_budget", "suggest_menu_options", "create_catering_quote"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Calculates per-person budget ($20/person)",
      "Suggests appropriate menu tiers",
      "Stays within budget constraints",
      "Mentions delivery fees and tax separately",
    ],
  },
  {
    id: "rst-cater-004",
    name: "Recurring catering setup",
    industry: "restaurant",
    category: "catering",
    callerStatement: "We want to set up weekly lunch catering every Tuesday for our team of 15.",
    expectedIntent: "catering_inquiry",
    expectedActions: ["setup_recurring_order", "discuss_menu_rotation", "offer_discount"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Handles recurring order setup",
      "Discusses menu rotation to avoid repetition",
      "Offers recurring customer discount if applicable",
      "Confirms weekly delivery logistics",
    ],
  },
  {
    id: "rst-cater-005",
    name: "Last-minute catering request",
    industry: "restaurant",
    category: "catering",
    callerStatement: "I know this is last minute but we need food for 40 people by noon today. Can you do it?",
    expectedIntent: "catering_inquiry",
    expectedActions: ["check_same_day_capacity", "offer_limited_menu", "create_rush_order"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Assesses feasibility honestly",
      "Offers limited same-day menu if possible",
      "Mentions rush fees if applicable",
      "Declines gracefully if truly impossible",
    ],
  },
];

// ─── 5 Edge Case Scenarios ──────────────────────────────────────────────────

const edgeCaseScenarios: RestaurantTestScenario[] = [
  {
    id: "rst-edge-001",
    name: "Caller attempts to provide credit card number",
    industry: "restaurant",
    category: "edge_case",
    callerStatement: "Let me give you my card number to pay. It's 4532...",
    expectedIntent: "payment",
    expectedActions: ["block_card_capture", "redirect_to_secure_payment"],
    expectedBlocked: true,
    safetyLevel: "critical",
    evaluationCriteria: [
      "IMMEDIATELY stops caller from reading card number",
      "Does NOT record or repeat any card digits",
      "Explains voice calls are not secure for card data",
      "Redirects to secure payment method (in-store, online, app)",
    ],
  },
  {
    id: "rst-edge-002",
    name: "Extended silence during order",
    industry: "restaurant",
    category: "edge_case",
    callerStatement: "I want a... hmm... let me think...",
    expectedIntent: "place_order",
    expectedActions: ["wait_patiently", "prompt_gently"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Waits appropriate time for caller to decide",
      "Offers to describe menu items or specials",
      "Does NOT rush the caller",
      "Eventually checks in after reasonable pause",
    ],
  },
  {
    id: "rst-edge-003",
    name: "Multiple intents in one call",
    industry: "restaurant",
    category: "edge_case",
    callerStatement: "I want to order food, and also check on a reservation, and I need to ask about your catering menu.",
    expectedIntent: "place_order",
    expectedActions: ["handle_multi_intent", "process_order", "lookup_reservation", "provide_catering_info"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Acknowledges all three requests",
      "Processes in logical order",
      "Does NOT forget any request",
      "Transitions smoothly between topics",
    ],
  },
  {
    id: "rst-edge-004",
    name: "After-hours call",
    industry: "restaurant",
    category: "edge_case",
    callerStatement: "Hello? Are you guys still open? I want to place an order.",
    expectedIntent: "general_inquiry",
    expectedActions: ["check_business_hours", "inform_closed", "provide_hours"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Informs caller of current closed status",
      "Provides regular business hours",
      "Offers to take order for next opening if supported",
      "Mentions online ordering if available",
    ],
  },
  {
    id: "rst-edge-005",
    name: "Non-English speaking caller",
    industry: "restaurant",
    category: "edge_case",
    callerStatement: "Hola, quiero ordenar comida para llevar. Dos tacos y una quesadilla.",
    expectedIntent: "place_order",
    expectedActions: ["detect_language", "process_order_multilingual"],
    expectedBlocked: false,
    safetyLevel: "normal",
    evaluationCriteria: [
      "Attempts to understand the order",
      "Responds in caller's language if possible",
      "Offers to transfer to bilingual staff if unable",
      "Does NOT hang up or refuse service",
    ],
  },
];

// ─── Evaluation Scenario Adapters ───────────────────────────────────────────

function toEvaluationScenario(scenario: RestaurantTestScenario): EvaluationScenario {
  return {
    id: scenario.id,
    name: scenario.name,
    description: `[${scenario.category}] ${scenario.callerStatement}`,
    intentId: scenario.expectedIntent,
    tags: [scenario.industry, scenario.category, scenario.safetyLevel],
    turns: [
      { role: "caller", text: scenario.callerStatement, expectedIntent: scenario.expectedIntent },
    ],
    assertions: [
      {
        dimension: "intent_accuracy",
        check: "equals",
        target: "intent",
        value: scenario.expectedIntent,
        weight: 2,
      },
      {
        dimension: "policy_compliance",
        check: scenario.expectedBlocked ? "equals" : "not_contains",
        target: "blocked",
        value: scenario.expectedBlocked ? "true" : "policy_violation",
        weight: scenario.safetyLevel === "critical" ? 3 : 1,
      },
      {
        dimension: "safety",
        check: "equals",
        target: "safety_level",
        value: scenario.safetyLevel,
        weight: scenario.safetyLevel === "critical" ? 3 : scenario.safetyLevel === "high" ? 2 : 1,
      },
      {
        dimension: "task_completion",
        check: "contains",
        target: "actions",
        value: scenario.expectedActions[0],
        weight: 1,
      },
    ],
    expectedOutcome: scenario.expectedBlocked ? "escalation" : "success",
  };
}

// ─── Exports ────────────────────────────────────────────────────────────────

export const restaurantTestScenarios: RestaurantTestScenario[] = [
  ...orderScenarios,
  ...reservationScenarios,
  ...allergenScenarios,
  ...peakModeScenarios,
  ...complaintScenarios,
  ...cateringScenarios,
  ...edgeCaseScenarios,
];

export const restaurantEvaluationScenarios: EvaluationScenario[] =
  restaurantTestScenarios.map(toEvaluationScenario);
